/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {
    private OnlineCoursePanel OLcourse;
    private OnsiteCoursePanel OScourse;
    private StudentGradePanel SGrade;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnCourse = new com.k33ptoo.components.KButton();
        btnGrade = new com.k33ptoo.components.KButton();
        btnInstructor = new com.k33ptoo.components.KButton();
        jPanel1 = new javax.swing.JPanel();
        tpMain = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnCourse.setText("COURSE");
        btnCourse.setFont(new java.awt.Font("Krona One", 0, 10)); // NOI18N
        btnCourse.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCourse.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnCourse.setkBorderRadius(0);
        btnCourse.setkEndColor(new java.awt.Color(255, 255, 255));
        btnCourse.setkForeGround(new java.awt.Color(211, 65, 208));
        btnCourse.setkHoverEndColor(new java.awt.Color(99, 65, 180));
        btnCourse.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnCourse.setkHoverStartColor(new java.awt.Color(248, 90, 202));
        btnCourse.setkPressedColor(new java.awt.Color(22, 255, 0));
        btnCourse.setkStartColor(new java.awt.Color(255, 255, 255));
        btnCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseActionPerformed(evt);
            }
        });

        btnGrade.setText("STUDENT GRADE");
        btnGrade.setFont(new java.awt.Font("Krona One", 0, 10)); // NOI18N
        btnGrade.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnGrade.setkBorderRadius(0);
        btnGrade.setkEndColor(new java.awt.Color(255, 255, 255));
        btnGrade.setkForeGround(new java.awt.Color(211, 65, 208));
        btnGrade.setkHoverEndColor(new java.awt.Color(99, 65, 180));
        btnGrade.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnGrade.setkHoverStartColor(new java.awt.Color(248, 90, 202));
        btnGrade.setkPressedColor(new java.awt.Color(22, 255, 0));
        btnGrade.setkStartColor(new java.awt.Color(255, 255, 255));
        btnGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeActionPerformed(evt);
            }
        });

        btnInstructor.setText("COURSE INTRUCTOR");
        btnInstructor.setAlignmentY(0.0F);
        btnInstructor.setFont(new java.awt.Font("Krona One", 0, 10)); // NOI18N
        btnInstructor.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnInstructor.setkBorderRadius(0);
        btnInstructor.setkEndColor(new java.awt.Color(255, 255, 255));
        btnInstructor.setkForeGround(new java.awt.Color(211, 65, 208));
        btnInstructor.setkHoverEndColor(new java.awt.Color(99, 65, 180));
        btnInstructor.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnInstructor.setkHoverStartColor(new java.awt.Color(248, 90, 202));
        btnInstructor.setkPressedColor(new java.awt.Color(22, 255, 0));
        btnInstructor.setkStartColor(new java.awt.Color(255, 255, 255));
        btnInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(btnCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(btnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 51, 153));

        tpMain.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1000, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInstructorActionPerformed

    private void btnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseActionPerformed
        if(OScourse == null) {
        OScourse = new OnsiteCoursePanel();
        OLcourse = new OnlineCoursePanel();
        
        tpMain.addTab("ONSITE COURSE", OScourse);
        tpMain.addTab("ONLINE COURSE", OLcourse);
        }
        tpMain.setSelectedComponent(OScourse);
           
    }//GEN-LAST:event_btnCourseActionPerformed

    private void btnGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeActionPerformed
        if(SGrade == null) {
        SGrade = new StudentGradePanel();
        tpMain.addTab("STUDENT GRADE", SGrade);
        }
        tpMain.setSelectedComponent(SGrade);
    }//GEN-LAST:event_btnGradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnCourse;
    private com.k33ptoo.components.KButton btnGrade;
    private com.k33ptoo.components.KButton btnInstructor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane tpMain;
    // End of variables declaration//GEN-END:variables
}
