/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import BLL.CourseBLL;
import BLL.OnlinecourseBLL;
import DAL.Course;
import DAL.OnlineCourse;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class OnlineCoursePanel extends javax.swing.JPanel {
    private MainForm mainform;
    private DefaultTableModel tblonlinemodel;
    /**
     * Creates new form OnlineCoursePanel
     */
    public OnlineCoursePanel() {
        initComponents();
        initTable();
        loadDataToTable();
        
    }
private void initTable() {
        tblonlinemodel = new DefaultTableModel();
        tblonlinemodel.setColumnIdentifiers(new String[] {"CourseID  ","Title","Credits","Department name", "URL"});
        tblonline.setModel(tblonlinemodel);
    }
    private void loadDataToTable() {
        try {
            OnlinecourseBLL bll = new OnlinecourseBLL();
            List<OnlineCourse> list = bll.LoadOnline(WIDTH);
            tblonlinemodel.setRowCount(0);
            for(OnlineCourse it : list) {
                tblonlinemodel.addRow(new Object[] {
                it.getCourseID(),it.getTitle(),it.getCredits(),it.getDepartmentName(), it.getUrl()});
            }
            tblonlinemodel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private boolean checktxtCourseID() throws HeadlessException {
        StringBuilder sb = new StringBuilder();
        if(txtCourseID.getText().equals("")){
            sb.append("Mã khóa học không được để trống");
        }
        if (sb.length() >0) {
            JOptionPane.showMessageDialog(mainform, sb, "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            txtCourseID.setBackground(Color.red);
            return true;
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblonline = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCourseTitle = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btnSearch = new com.k33ptoo.components.KButton();
        btnUpdate = new com.k33ptoo.components.KButton();
        btnDelete = new com.k33ptoo.components.KButton();
        btnReset = new com.k33ptoo.components.KButton();
        btnAdd = new com.k33ptoo.components.KButton();
        txtDepName = new javax.swing.JTextField();
        txtCourseID = new javax.swing.JTextField();
        btnshowtbl = new com.k33ptoo.components.KButton();

        setPreferredSize(new java.awt.Dimension(1000, 660));

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 800));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(248, 90, 202));
        kGradientPanel1.setkGradientFocus(700);
        kGradientPanel1.setkStartColor(new java.awt.Color(99, 65, 180));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque (false);

        tblonline.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        tblonline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblonline.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer) tblonline.getDefaultRenderer(Object.class)).setBackground (new Color (0,0,0,0));
        tblonline.setForeground (Color.WHITE);
        tblonline.setGridColor(new java.awt.Color(255, 255, 255));
        tblonline.setOpaque (false);
        ((DefaultTableCellRenderer) tblonline.getDefaultRenderer (Object.class)).setOpaque (false);
        tblonline.setShowGrid (true);

        tblonline.getTableHeader().setFont (new Font ("Open Sans", Font.BOLD, 14));

        tblonline.getTableHeader().setBackground (new Color (255,238,125));
        tblonline.getTableHeader().setForeground (new Color (255,255,255));
        tblonline.getTableHeader().setOpaque (false);
        tblonline.setRowHeight(25);
        tblonline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblonlineMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblonline);

        jLabel1.setFont(new java.awt.Font("Krona One", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ONLINE COURSE");

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CourseID:");

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course Title:");

        txtSearch.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSearchMousePressed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department Name:");

        txtCourseTitle.setEditable(false);
        txtCourseTitle.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtCourseTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseTitleActionPerformed(evt);
            }
        });

        txtCredits.setEditable(false);
        txtCredits.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Credits:");

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Course Title:");

        jLabel9.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("URL:");

        txtUrl.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        btnSearch.setBorder(null);
        btnSearch.setText("SEARCH");
        btnSearch.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnSearch.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnSearch.setkEndColor(new java.awt.Color(68, 45, 124));
        btnSearch.setkHoverEndColor(new java.awt.Color(83, 76, 152));
        btnSearch.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSearch.setkHoverStartColor(new java.awt.Color(183, 103, 255));
        btnSearch.setkPressedColor(new java.awt.Color(255, 238, 125));
        btnSearch.setkStartColor(new java.awt.Color(99, 65, 180));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnUpdate.setkEndColor(new java.awt.Color(68, 45, 124));
        btnUpdate.setkHoverEndColor(new java.awt.Color(83, 76, 152));
        btnUpdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdate.setkHoverStartColor(new java.awt.Color(183, 103, 255));
        btnUpdate.setkPressedColor(new java.awt.Color(255, 238, 125));
        btnUpdate.setkStartColor(new java.awt.Color(99, 65, 180));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnDelete.setkEndColor(new java.awt.Color(68, 45, 124));
        btnDelete.setkHoverEndColor(new java.awt.Color(83, 76, 152));
        btnDelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDelete.setkHoverStartColor(new java.awt.Color(183, 103, 255));
        btnDelete.setkPressedColor(new java.awt.Color(255, 238, 125));
        btnDelete.setkStartColor(new java.awt.Color(99, 65, 180));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnReset.setkEndColor(new java.awt.Color(68, 45, 124));
        btnReset.setkHoverEndColor(new java.awt.Color(83, 76, 152));
        btnReset.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnReset.setkHoverStartColor(new java.awt.Color(183, 103, 255));
        btnReset.setkPressedColor(new java.awt.Color(255, 238, 125));
        btnReset.setkStartColor(new java.awt.Color(99, 65, 180));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnAdd.setkEndColor(new java.awt.Color(68, 45, 124));
        btnAdd.setkHoverEndColor(new java.awt.Color(83, 76, 152));
        btnAdd.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAdd.setkHoverStartColor(new java.awt.Color(183, 103, 255));
        btnAdd.setkPressedColor(new java.awt.Color(255, 238, 125));
        btnAdd.setkStartColor(new java.awt.Color(99, 65, 180));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtDepName.setEditable(false);
        txtDepName.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtDepName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepNameActionPerformed(evt);
            }
        });

        txtCourseID.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtCourseID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCourseIDKeyPressed(evt);
            }
        });

        btnshowtbl.setText("...");
        btnshowtbl.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnshowtbl.setkEndColor(new java.awt.Color(68, 45, 124));
        btnshowtbl.setkHoverEndColor(new java.awt.Color(83, 76, 152));
        btnshowtbl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnshowtbl.setkHoverStartColor(new java.awt.Color(183, 103, 255));
        btnshowtbl.setkPressedColor(new java.awt.Color(255, 238, 125));
        btnshowtbl.setkStartColor(new java.awt.Color(99, 65, 180));
        btnshowtbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowtblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnshowtbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCredits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUrl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(77, 77, 77)
                                .addComponent(txtCourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDepName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(281, 281, 281))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnshowtbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(56, 56, 56)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(txtDepName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblonlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblonlineMouseClicked
        try {
            int row = tblonline.getSelectedRow();
            if(row >= 0){
                int id = (Integer) tblonline.getValueAt(row, 0);
                OnlinecourseBLL bll = new OnlinecourseBLL();
                OnlineCourse oc = bll.getOnline(id);

                if(oc != null) {
                    txtCourseID.setText(String.valueOf(oc.getCourseID()));
                    txtCourseTitle.setText(oc.getTitle());
                    txtCredits.setText(String.valueOf(oc.getCredits()));
                    txtDepName.setText(oc.getDepartmentName());
                    txtUrl.setText(oc.getUrl());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(mainform, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblonlineMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        try{
            OnlinecourseBLL bll = new OnlinecourseBLL();
            List<OnlineCourse> list = bll.findbyTitle(txtSearch.getText());

            initTable();
            for(OnlineCourse it : list){
                tblonlinemodel.addRow(new Object[] {
                    it.getCourseID(),it.getTitle(),it.getCredits(),it.getDepartmentName(), it.getUrl()});
        }

        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(mainform,"Khóa học không tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtCourseTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseTitleActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try{
            OnlinecourseBLL bll = new OnlinecourseBLL();
            List<OnlineCourse> list = bll.findbyTitle((txtSearch.getText()));

            if(list.isEmpty()){
                JOptionPane.showMessageDialog(mainform,"Khóa học không tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            }else{
                for(OnlineCourse oc : list){
                    txtCourseID.setText(String.valueOf(oc.getCourseID()));
                    txtCourseTitle.setText((oc.getTitle()));
                    txtCredits.setText(String.valueOf(oc.getCredits()));
                    txtDepName.setText(oc.getDepartmentName());
                    txtUrl.setText(oc.getUrl());
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(mainform,"Khóa học không tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(checktxtCourseID())return;
        try{
            OnlineCourse oc = new OnlineCourse();
            oc.setCourseID(Integer.parseInt(txtCourseID.getText()));
            oc.setUrl(txtUrl.getText());
            OnlinecourseBLL bll = new OnlinecourseBLL();

            if(bll.updateOnline(oc) >0){
                JOptionPane.showMessageDialog(mainform, "Cập nhật khóa học thành công");
                txtCourseID.setText("");
                txtCourseTitle.setText("");
                txtCredits.setText("");
                txtDepName.setText("");
                txtUrl.setText("");
                loadDataToTable();
            }else{
                JOptionPane.showMessageDialog(mainform,"Cập nhật khóa học thất bại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(mainform,"Cập nhật khóa học thất bại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(checktxtCourseID())return;
        if(JOptionPane.showConfirmDialog(mainform, "Bạn có muốn xóa không?", "Hỏi"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION)
    {
        return;
        }
        try{
            OnlinecourseBLL bll = new OnlinecourseBLL();

            if(bll.deleteOnline(Integer.parseInt(txtCourseID.getText())) ==0){
                txtCourseID.setText("");
                txtCourseTitle.setText("");
                txtCredits.setText("");
                txtDepName.setText("");
                txtUrl.setText("");
                JOptionPane.showMessageDialog(mainform,"Xóa khóa học thất bại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(mainform, "Xóa khóa học thành công");
                txtCourseID.setText("");
                txtCourseTitle.setText("");
                txtCredits.setText("");
                txtDepName.setText("");
                txtUrl.setText("");
                loadDataToTable();
            }

        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(mainform,"Khóa học không tồn tại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtCourseID.setText("");
        txtCourseTitle.setText("");
        txtCredits.setText("");
        txtDepName.setText("");
        txtUrl.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(checktxtCourseID())return;
        try{
            OnlineCourse oc = new OnlineCourse();
            oc.setCourseID(Integer.parseInt(txtCourseID.getText()));
            oc.setUrl(txtUrl.getText());
            OnlinecourseBLL bll = new OnlinecourseBLL();

            if(bll.addOnline(oc) >0){
                JOptionPane.showMessageDialog(mainform, "Thêm khóa học thành công");
                txtCourseID.setText("");
                txtCourseTitle.setText("");
                txtCredits.setText("");
                txtDepName.setText("");
                txtUrl.setText("");
                loadDataToTable();
            }else{
                JOptionPane.showMessageDialog(mainform,"Thêm khóa học thất bại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(mainform,"Thêm khóa học thất bại" , "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtDepNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepNameActionPerformed

    private void txtCourseIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCourseIDKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
                CourseBLL bll = new CourseBLL();
                Course oc = bll.getCourse(Integer.parseInt(""+txtCourseID.getText()));
                if(oc.getTitle().isBlank() && oc.getCredits() ==0 && oc.getDepartmentName().isBlank()){
                    JOptionPane.showMessageDialog(mainform, "CourseID không tồn tại");
                }
                txtCourseTitle.setText(""+oc.getTitle());
                txtCredits.setText(""+ oc.getCredits());
                txtDepName.setText(""+ oc.getDepartmentName());
            }catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(mainform, "CourseID không tồn tại");
            }
        }
    }//GEN-LAST:event_txtCourseIDKeyPressed

    private void btnshowtblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowtblActionPerformed
        TableCourse tc = new TableCourse();
        try{
            tc.list();

        }catch (Exception ex) {
            Logger.getLogger(TableCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
        tc.setVisible(true);
    }//GEN-LAST:event_btnshowtblActionPerformed

    private void txtSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAdd;
    private com.k33ptoo.components.KButton btnDelete;
    private com.k33ptoo.components.KButton btnReset;
    private com.k33ptoo.components.KButton btnSearch;
    private com.k33ptoo.components.KButton btnUpdate;
    private com.k33ptoo.components.KButton btnshowtbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tblonline;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseTitle;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtDepName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
